runtime: python39
instance_class: F4
# service: commi

entrypoint: python manage.py runserver 0.0.0.0:$PORT

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/