# Generated by Django 4.2.1 on 2023-06-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='solution',
            field=models.TextField(blank=True, help_text='The solution of the proposal', null=True, verbose_name='solution'),
        ),
    ]
