# Generated by Django 3.2.2 on 2023-06-18 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier', primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(help_text='The name of the resource', max_length=500, verbose_name='name')),
                ('timetable', models.CharField(help_text='The timetable of the resource', max_length=500, verbose_name='timetable')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='The date of creation', verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, help_text='The date of the last modification', verbose_name='modification date')),
                ('deletion_date', models.DateTimeField(blank=True, help_text='The date of deletion', null=True, verbose_name='deletion date')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier', primary_key=True, serialize=False, verbose_name='UUID')),
                ('slot', models.CharField(help_text='The slot of the resource', max_length=200, verbose_name='slot')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='The date of creation', verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, help_text='The date of the last modification', verbose_name='modification date')),
                ('deletion_date', models.DateTimeField(blank=True, help_text='The date of deletion', null=True, verbose_name='deletion date')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bookings.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier', primary_key=True, serialize=False, verbose_name='UUID')),
                ('status', models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('ENJOYED', 'ENJOYED')], default='RECEIVED', help_text='The status of the booking', max_length=10, verbose_name='status')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='The date of creation', verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, help_text='The date of the last modification', verbose_name='modification date')),
                ('deletion_date', models.DateTimeField(blank=True, help_text='The date of deletion', null=True, verbose_name='deletion date')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bookings.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
