# Generated by Django 3.2.2 on 2023-06-18 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date of booking', verbose_name='booking date'),
            preserve_default=False,
        ),
    ]
