# Generated by Django 3.2.2 on 2023-06-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='timetable',
            field=models.TextField(help_text='The timetable of the resource', max_length=500, verbose_name='timetable'),
        ),
    ]
