# Generated by Django 3.2.2 on 2023-06-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_resource_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(default=True, help_text='The active status of the resource', verbose_name='status'),
            preserve_default=False,
        ),
    ]
