# Generated by Django 3.2.2 on 2023-06-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_resource_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='The active status of the schedule', verbose_name='status'),
            preserve_default=False,
        ),
    ]
