# Generated by Django 3.2.2 on 2023-06-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code_img',
            field=models.ImageField(blank=True, help_text='The qr of the booking', null=True, upload_to='bookings/img/qr/', verbose_name='qr image'),
        ),
    ]
