# Generated by Django 3.2.2 on 2023-06-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_qr_code_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='qr_code_img',
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_img_url',
            field=models.CharField(blank=True, help_text='The qr path of the booking', max_length=1000, null=True, verbose_name='qr image'),
        ),
    ]
