# Generated by Django 3.2.2 on 2023-06-21 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0008_auto_20230621_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.CharField(help_text='The number of the building', max_length=10, verbose_name='bldg. num.')),
                ('building_character', models.CharField(help_text='The name of the resource', max_length=10, verbose_name='bldg. char.')),
                ('door_number', models.CharField(help_text='The name of the resource', max_length=10, verbose_name='door num.')),
                ('door_character', models.CharField(help_text='The name of the resource', max_length=10, verbose_name='door char.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
